Project

packages
```{r}
# install.packages("rvest")
library(rvest)
```

```{r}
# 1. Extract the full name of ISO Country code from https://help.adjust.com/en/article/countriesby-region 

# Read the HTML page
page <- read_html("https://help.adjust.com/en/article/countries-by-region")

# Extract the first table
country_table <- data.frame(html_table(html_element(page, "table"),na = character(0)))

# Change all country codes to uppercase to match music_table
country_table$Country.code <- toupper(country_table$Country.code)

# Add the full name of the region
regionName <- c("EMEA" = "Europe, the Middle East and Africa",
                "NA" = "North America",
                "LATAM" = "Latin America",
                "APAC" = "Asia-Pacific")

country_table$Region_name <- regionName[country_table$Region]
head(country_table)
```
```{r}
# 2. convert the country to the fill name
# Load dataset
music_data <- read.csv("top_Trending_songs.csv")

# Change the country of the first fifty records to ‘Global’
music_data$country[1:50] <- "Global"

# Change the two date-related columns to date format
music_data$snapshot_date <- as.Date(music_data$snapshot_date)
music_data$album_release_date <- as.Date(music_data$album_release_date)
head(music_data)

```


```{r}
# Merge on the country code
music_data <- merge(music_data,
                    country_table,
                    by.x = "country",
                    by.y = "Country.code",
                    all.x = TRUE)


# Change all relative information of Global to Global
colnames(music_data)[colnames(music_data) == "Country"] <- "Name"
music_data$Name[music_data$country == "Global"] <- "Global"
music_data$Region_name[music_data$country == "Global"] <- "Global"

```


```{r}
# 3. Label the valence and speechiness value by the following table
# Category/Range    | < 1st quartile  | 1st quartile ~ Median | Median ~ 3rd quartile | > 3rd quartile
# speechiness       | Pure music      | Song and words balaced| Word leads music      | Words oriented
# valence           | darkness        | Gray feeling          | positive              | brightness


# Calculate the quartile of speechiness and valence
speechinessQ1 <- summary(music_data$speechiness)["1st Qu."]
speechinessQ2 <- summary(music_data$speechiness)["Median"]
speechinessQ3 <- summary(music_data$speechiness)["3rd Qu."]

valenceQ1 <- summary(music_data$valence)["1st Qu."]
valenceQ2 <- summary(music_data$valence)["Median"]
valenceQ3 <- summary(music_data$valence)["3rd Qu."]

# Add new columns to save each labels
music_data$speechiness_label <- ifelse(music_data$speechiness < speechinessQ1, "Pure music",
                                       ifelse(music_data$speechiness < speechinessQ2, "Song and words balaced",
                                              ifelse(music_data$speechiness < speechinessQ3, "Word leads music",
                                                     "Words oriented")))

music_data$valence_label <- ifelse(music_data$valence < valenceQ1, "darkness",
                                       ifelse(music_data$valence < valenceQ2, "Gray feeling",
                                              ifelse(music_data$valence < valenceQ3, "positive",
                                                     "brightness")))

```

```{r}
# Reorder columns
music_data <- music_data[, c("Name", "country","spotify_id", "name", "artists", "daily_rank",
                             "daily_movement", "weekly_movement", "snapshot_date",
                             "popularity", "is_explicit", "duration_ms", "album_name",
                             "album_release_date", "danceability", "energy", "key",
                             "loudness", "mode", "speechiness", "speechiness_label",
                             "acousticness", "instrumentalness", "liveness", "valence",
                             "valence_label", "tempo","time_signature", "Region_name")]

music_data_withoutNA <- music_data[!is.na(music_data$Name), ]
```


```{r}
# Save the Final dataset
write.csv(music_data, "Music_Final.csv", row.names = FALSE)
write.csv(music_data_withoutNA, "Music_Final_withoutNA.csv", row.names = FALSE)

```


